github/opensourcefriday

config/initializers/figaro.rb

This fixes the broken `master` build (oops) from merging the PR that was opened before there was CI on this repository.

initializers/figaro: don't require keys for test.

---

app/views/home/contributors.html.erb
app/views/home/index.html.erb
app/views/home/maintainers.html.erb

General bit of polishing to supplement https://github.com/ossfriday/ossfriday/pull/28.
Not done by any means, but I simplified language where possible and tried to make it a bit more aspirational. I think we should loop Steph/Erin in to get it to the next place.
A few suggestions:
* **Make contributor page the homepage**: I thought the homepage would be the Contributors page, not the Company page. We're marketing primarily to potential contributors, right? And it seems that developers would be the ones to advocate and drive this idea internally, not an exec who doesn't really understand open source yet.
* **Company page needs clearer action items.** I don't think "add to calendar" is the right one. It's probably more like, understand what this thing is + be reassured it's good for …

Edit website copy

---

app/views/home/maintainers.html.erb

Noticed the green button was off-center, at least for me. I think this fixes it?
Before:
After:

Center green button on Maintainers page

---

app/controllers/users_controller.rb
app/views/users/show.html.erb

Using the user public events API we can get the last 1000 events. If any of these are relevant maintainer-like events then they will be displayed. In my case, I make too many events for any to be displayed for April 23rd (my last relevant Friday). Another option is to not filter these maintainer-like events to only Fridays. Similarly, they could be interspersed with pull requests.
~Also in this PR is obtaining a more complete set of pull request search results and displaying the repository for each result. Arguably the repository could be turned into another section heading like date.~ moved to #48
CC @nayafia for thoughts on whether this is better/worse than the status quo (in terms of events, the rest will probably go in anyway).

Get some other user events.

---

Gemfile
Gemfile.lock
config/environments/production.rb

Octokit queries are expensive and are cached but this wasn’t set up in production yet. Switch to using Redis for caching both in production and keep using memory caching in development.

Use Redis for caching

---

bin/setup
script/bootstrap

We vendor NPM modules in the repository so remove the unnecessary, heavy dependency for most contributors.

NPM is not needed to bootstrap

---

app/views/layouts/_calendar.html.erb
app/views/users/show.html.erb
test/test_helper.rb

Just to disclose that this is a public page.
Also, tweak the calendar wording and it's "Open Source Friday" not "Open Source Fridays".

users/show: provide link to share page.

---

.rubocop.yml
app/controllers/users_controller.rb
config/environments/development.rb
test/controllers/users_controller_test.rb
test/test_helper.rb

The previous approach is diff-heavy and annoying.

rubocop: trailing commas on hashes.

---

app/views/users/show.html.erb

The non-logged-in view of the user page was incorrectly showing 'Hi @username, this
is your page'.

Fix incorrect nesting in user page

---

README.md

If you don't have the correct Ruby version installed, per the
.ruby-version file, then `bundle exec figaro install` will
blow up with a _version not installed_ error.
If you take off the bundle exec, then it tries to run figaro,
which you may not have at this point.
We could update the instructions to say
gem install figaro && figaro install
however that will generate a config/application.yml with
commented out environment variables in it, none of which we need.
There is a config/application.example.yml file which lists the
variables that we do need.
To bypass all the potential errors of trying to work with a gem
before running bootstrap and setup, this instructs people to
copy the example yaml and fill it out according to the tokens
generated for the oauth app.
This also is explicit …

Update development instructions regarding figaro

---

app/controllers/users_controller.rb

The `/users/:username` page was showing a list of dates, many of which
were not Fridays.
Upon inspection it turned out that all of these were created on a
Friday, but they were being listed by the date that they were closed or
merged.
Since we're specifically calling out Fridays with the heading
> N pull requests opened on Fridays in the last year:
it feels confusing to have non-Fridays listed. Also, due to the events being ordered by their creation date but grouped by the display date, the dates were being shown out of order. (June 2, June 6, May 25...)
This changes the list to display based on the pull request **created at** date.

List pull requests on user page by created date

---

db/migrate/20170608210301_add_subscribed_to_users.rb
db/schema.rb

The actual subscription is tracked in MailChimp, however we need to know whether or not to
display the form.
I don't want to have to ask MailChimp about their subscription every time just to show
the page, but I also acknowledge that I tend to be a bit more nervous than other folks about adding in-request dependencies on external APIs. Maybe it's fine to just rely on the mailchimp API when showing the user page.
On the other hand, we're already relying on the GitHub API... so what's one more external HTTP call?
Then again, we don't know what email they'd sign up with. We may or may not have the primary email on their GitHub account (if it's public), so we can't rely on a call to MailChimp, because we won't necessarily know what to ask about.
What do you think @MikeMcQuaid?

Add migration to track newsletter subscriptions

---

script/bootstrap
script/cibuild
script/server

- Make formatting consistent between scripts
- Only print out "Installing Ruby" when we're actually doing so
- Make `script/cibuild` always run both tests and RuboCop in case both are failing to ensure output is seen from both (CC @kytrinyx)

Improve script behaviour and formatting.

---

app/models/user.rb
test/controllers/users_controller_test.rb

As noted in #66 users OAuth tokens were not being set correctly. This is because they were using `auth.info.token` rather than `auth.credentials.token` to get them back from GitHub/Devise. Fix this up and additionally set the token for those users that are already stored in the database but are missing this attribute.
Closes #66.

user: correctly set OAuth token.

---

app/controllers/users_controller.rb
app/views/users/show.html.erb

- Allow using a `?user_exists=1` parameter in development to view any GitHub user's   PRs/events as if they had joined Open Source Friday. This is useful in testing PRs such as this one where you want to test on a variety of different user data.
- Rather than displaying two separate lists of PRs and events show them interleaved in a single list.
- Show PRs for the last 3 months rather than 12.
- Pluralise "pull requests" correctly.

users/show: combine PRs and events.

---

app/views/users/show.html.erb

Add a signup form for the GitHub Open Source mailing list. An easier alternative to using MailChimp's API.
Closes #65.

users/show: add GitHub Open Source mailing list.

---

app/models/user.rb
config/initializers/devise.rb
db/migrate/20170111052513_devise_create_users.rb
db/migrate/20170608210301_add_subscribed_to_users.rb
db/migrate/20170620141001_cleanup_users_columns.rb
db/schema.rb
test/controllers/users_controller_test.rb
test/fixtures/users.yml

Let's not store we don't need. We don't need to store/use:
- the user's GitHub UID (use username instead)
- the user's name (look up/cache from the API when needed)
- the user's email (this isn't always returned by the API, isn't used)
- whether the user subscribed to the newsletter (isn't used)
Also, add a new index to look up users by username (as we're no longer doing so by UID or email).

Remove unused database columns

---

Gemfile
Gemfile.lock
app/controllers/home_controller.rb
config/application.rb
config/routes.rb

Use the `failbot` gem to enable exception handling on GitHub's internal error tracking tool (Haystack). Also, add an endpoint for doing testing of exceptions.

Add exception handling.

---

app/models/user.rb
app/views/layouts/_nav.html.erb
config/initializers/devise.rb

- Update the OAuth token if it differs from the one stored in the database (either it's missing in the database or has changed)
- Use GET to sign out now that we're not using JQuery and fix sign out

Fix sign-in/sign-out flow

---

app/views/users/show.html.erb

This was smushed in a merge resolution but re-add the change from #89 to only link companies that begin with `@`.
Fixes #103.

users/show: refix company link.

---

Gemfile.lock

Do this to avoid the exception described in:
https://github.com/puma/puma/issues/915
https://github.com/rack/rack/issues/1077
by upgrading to 2.0.3 which includes the pull request:
https://github.com/rack/rack/pull/1080

Update rack gem

---

app/controllers/users_controller.rb
config/initializers/octokit_cache.rb

Instead of using a split approach between Octokit caching and Rails caching cache the processed metadata from the Octokit requests. This has the benefits of avoiding reprocessing on every request and not storing in the cache data that we don't need for user display.
This involves changes to the cache keys and invalidating all existing cache entries but this will be better for long-term resource usage after the initial public ship.

Improve Rails cache utilisation

---

app/assets/stylesheets/addtocalendar.scss

Fix wrong font in the Add to Calendar dropdown, as per #136.
cc @MikeMcQuaid 🎉

Wrong font in calendar dropdown

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/models/user.rb
config/initializers/locale.rb
db/migrate/20170712033920_add_language_to_users.rb
db/schema.rb
test/controllers/application_controller_test.rb
test/controllers/users_controller_test.rb
test/fixtures/users.yml

Here is a follow-up PR that split  logic from #129 
- Select language from Accept-Language header.
- Use language preference for login user.
- Accept locale url parameter when exist.
Signed-off-by: Hiroshi Miura <miurahr@linux.com>

Internationalise application

---

config/locales/en.yml
config/locales/ja.yml

There was a double `:` here.
CC @miurahr.

Fix "joined" locale key

---

.travis.yml

This avoids duplicate jobs on non-fork PRs.

travis.yml: don't build all branches.

---

Gemfile.lock
script/cibuild

I always forget you also need to run `bundle install` for Heroku apps so the Gemfile.lock is updated. Add a `script/cibuild` check to make sure no-one makes this mistake in future.

Fix Ruby 2.5.1 bump

---

app/helpers/application_helper.rb
config/initializers/locale.rb

- `application_helper`: capitalise language name (otherwise `francais` is shown)
- `locale`: reorder languages to look a bit nicer to me

Tweak French translation

---

config/initializers/locale.rb
config/languages.yml

Hello,
Where we can watch alpha version?
https://opensourcefriday.com/?locale=fa
Target: https://github.com/github/opensourcefriday/pull/571
- Adding to available locales
- Adding to languages.yml -  `fa: Persian (فارسی)`
Best,
Max Base
Open Source Maintainer on GitHub

Adding Persian to Whitelist locales

---

.github/workflows/tests.yml

It was previously not installed and was started by default on installation. This should handle the both the case where it's installed already and when it's newly installed.

workflows/tests: start postgres service.

---

.github/workflows/tests.yml
Gemfile.lock

If this isn't set properly it will break Heroku deploys.

Ensure the correct Ruby version is in Gemfile.lock

---

app/views/layouts/application.html.erb

Hi,
Determining the language of a page can be effective in **SEO** in search results.
So I think we need to make that change.
http://127.0.0.1:3000/?locale=es
```
<!DOCTYPE html>
<html lang="es">
```
http://127.0.0.1:3000/?locale=en
```
<!DOCTYPE html>
<html lang="en">
```
http://127.0.0.1:3000/?locale=pt
```
<!DOCTYPE html>
<html lang="pt">
```
http://127.0.0.1:3000/?locale=fa
```
<!DOCTYPE html>
<html lang="fa">
```
etc...
Reference:
https://www.w3.org/International/questions/qa-html-language-declarations
If I made a mistake, help me.
Regards,
Max

Solve problem: set current language into html tag

---

app/views/home/businesses.html.erb
app/views/home/index.html.erb
app/views/home/maintainers.html.erb
app/views/layouts/_nav.html.erb
config/initializers/devise.rb

- Use `link_to` with `method: :post` instead of `button_to` for links
- Remove sign out (it seems to be broken entirely)

Cleanup Devise usage

---

Gemfile
Gemfile.lock
config/application.rb
config/environments/production.rb

Take-two of https://github.com/github/opensourcefriday/pull/825
Reverts github/opensourcefriday#829
Shortly: will include https://github.com/github/opensourcefriday/pull/828.
I think this will require Heroku configuration changes to work properly. 
This PR should be deployed successfully before merge. Ideally, we enable Heroku Review Apps for this repository before merge.

build(deps): bump rails from 6.0.3.4 to 6.1.0

---

config/environments/production.rb

The existing cache store configuration method was deprecated.

environments/production: use :mem_cache_store

---

Gemfile
Gemfile.lock

It's broken on Rails 6.1 and probably not needed any more:
https://github.com/romanbsd/heroku-deflater/issues/54

Gemfile: remove heroku-deflater

---

Gemfile
Gemfile.lock

It's no longer needed/used (I added it for my use and don't use it any more, `pp` for life).

Gemfile: remove awesome_print

---

.github/workflows/tests.yml

Here is a screen of a falling build caused by the current action:
The solution is to migrate to https://github.com/ruby/setup-ruby, which is being actively maintained. This is currently blocking the ability to merge the current active PRs

Migrate from "actions/setup-ruby@v1"

---

README.md

Remove Transifex

---

Gemfile

This PR addresses an offense that will be added once rubocop is updated to 1.22.0
see here: https://github.com/github/opensourcefriday/pull/1073/checks?check_run_id=3741681477#step:13:9

Addressing new rubocop 1.22.0 offense

---

app/views/home/index.html.erb

Hi
It was worth asking questions because James did a decent job of helping open source software.
I already ask about this issue from James(@varjmes), but he not replied. so I think we are allowed to remove "Your First PR".
As Mike (@MikeMcQuaid) agreed with it.
Related issue: https://github.com/github/opensourcefriday/issues/1103
P.S: I not removed "index.find.issue.first" field from language files, since I guess maybe we need "Your first Pull request" word in somewhere. (It already translated into a couple of languages)
Best,
Max

Remove: "Your first pull request" website link

---

_includes/footer.html

As described in the issue #1254 , the youtube iframe present in footer is not responsive ,i.e., it doesnt fix correctly on mobile screens. This PR fixes the issue.

fixed unresponsiveness of the iframe in footer

---

Gemfile

This is required to get a local dev environment running with
`script/server` , otherwise it errors out.
Fixes #1255
-----

Add webrick to Gemfile
