github/opensourcefriday

.travis.yml
There's no tests here yet but let's ensure that it doesn't get randomly broken by new things being added.
=> travis.yml: add basic CI.

README.md, config/initializers/figaro.rb
Detail how to get started. Mostly copy-pasted from 24 Pull Requests with some details tweaked to be specific to this project, Homebrew-related updates (which I personally know to be more correct) and a Figaro initialiser to :boom: if required environment variables aren’t set.
CC @andrew for review.
Fixes #5
=> Add Development section to README.

CONTRIBUTING.md, LICENSE.txt, README.md, app/views/home/companies.html.erb, app/views/home/contributors.html.erb, app/views/home/index.html.erb, app/views/home/maintainers.erb, app/views/layouts/application.html.erb
I spoke to @bkeepers and @kytrinyx about the wording here and they had some great suggestions that I've made here.
=> Tweak wording

.travis.yml, script/cibuild
Another pattern from https://github.com/github/scripts-to-rule-them-all.
=> Add and use script/cibuild.

README.md
Make it clear what order these steps are required.
Fixes #23.
=> README: reorder environment variables.

.gitignore, app/assets/stylesheets/application.scss, script/cibuild
And add it to CI so it doesn’t break again in future.
=> Fix asset compilation

app/views/layouts/application.html.erb
We'll be interested in who visits this page and where they click.
People who hate analytics are more than welcome to Adblock.
=> Add Analytics

app/views/home/contributors.html.erb, app/views/home/index.html.erb, app/views/home/maintainers.html.erb
Fill in all the text on all the pages from text and discussion on #16, #17 and #18 and remove missing placeholder images in favour of moving stuff around and more links to Open Source Guides.
=> Update text and remove more placeholders.

public/robots.txt
This generally makes it easier to have a site people can look at without making Google and friends pick it up yet.
=> robots.txt: ban robots until we go public.

app/views/home/index.html.erb, app/views/layouts/_auth_nav.html.erb, app/views/layouts/_nav.html.erb, app/views/layouts/application.html.erb
Also:
- Add navigation bar to main page.
- Add placeholder username link to verify sign-in worked and to link to user's profile (when built).
=> Re-add sign-in to navigation bar.

Gemfile, Gemfile.lock, app/controllers/users_controller.rb, app/models/user.rb, app/views/layouts/_nav.html.erb, app/views/users/show.html.erb, config/initializers/devise.rb, config/initializers/octokit_cache.rb, config/routes.rb, db/migrate/20170420081909_add_token_to_users.rb, db/schema.rb
Add pages for any user (with or without an account). This will look up their details on GitHub, display if they’ve joined the program and, if so, their contributions on Fridays for the last year.
=> Add user page.

app/assets/stylesheets/application.scss, app/views/home/index.html.erb, app/views/home/maintainers.html.erb
Also, kill the radial gradient on main header and adjust the padding on the header to fit the new button.
Fixes #42.
=> Add more "Sign up with GitHub" links.

app/controllers/users_controller.rb, app/views/users/show.html.erb
As requested by @kytrinyx in #40.
=> Add GitHub bio to users page.

app/views/home/businesses.html.erb, app/views/home/index.html.erb, app/views/home/maintainers.html.erb
Closes #35. Copy updates based on Erin and Steph's edits.
There are a couple things I wasn't sure about, cc @mikemcquaid for thoughts (see in-line review)
=> Finalize copy

app/controllers/users_controller.rb, app/views/users/show.html.erb
Obtain a more complete set of pull request search results and display the repository for each result. Arguably the repository could be turned into another section heading like date.
=> Cleanup users controller/view.

config/environments/production.rb
We have a login point (that redirects to SSL) so may as well make everything use it now.
=> Force SSL to be always on.

.rubocop.yml, Brewfile, Gemfile, Gemfile.lock, Rakefile, app/controllers/application_controller.rb, app/controllers/omniauth_callbacks_controller.rb, app/controllers/users_controller.rb, app/mailers/application_mailer.rb, app/models/user.rb, config.ru, config/application.rb, config/boot.rb, config/environment.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, config/initializers/assets.rb, config/initializers/devise.rb, config/initializers/new_framework_defaults.rb, config/initializers/session_store.rb, config/routes.rb, config/spring.rb, script/cibuild, test/models/user_test.rb, test/test_helper.rb
Run on CI runs, apply some autocorrection and general suggested fixes.
=> Enable Rubocop

Gemfile
Merge conflict fail on my part.
=> Gemfile: remove accidentally removed gem.

app/views/home/businesses.html.erb, app/views/layouts/_calendar.html.erb, app/views/layouts/application.html.erb, app/views/users/show.html.erb
Add a flash for errors that's displayed at the top of the page. Also, tweak the styling for the calendar and the Open Source Friday activity page URL for sharing to be more consistent and pretty.
=> Add flash, tweak calendar/share styles.

Gemfile, Gemfile.lock, config/environments/production.rb
- gzip all pages
- set better expiration headers for static resources
=> Speedup Heroku rendering a bit

app/controllers/users_controller.rb
This allows us a bit more control over e.g. avoiding unnecessary event queries when there's not enough public event data to make it worthwhile.
=> users_controller: manually paginate Octokit.

config/environments/production.rb
It seems the recommendation is for this to be further in the future.
=> Bump asset expiry to 10 years

public/robots.txt
We're almost ready so may as well get this a click away.
=> robots.txt: allow the pages to be crawled.

Gemfile, Gemfile.lock, config/cable.yml, config/environments/production.rb, config/puma.rb
- Use memcached and rack-cache in production
- Use recommended Heroku puma configuration
- Removed unused `config/cable.yml`
=> Various performance tweaks

app/assets/javascripts/application.js, app/assets/javascripts/calendar.js, app/views/home/businesses.html.erb, app/views/home/index.html.erb, app/views/home/maintainers.html.erb, config/environments/production.rb
- Remove JQuery dependency
- Use correct sized avatars
- Fix Expires date (cannot be >1 year and be valid)
=> Page load time tweaks

app/views/users/show.html.erb
Only link to companies if they start with `@` and then ensure the `@` is stripped for the link.
CC @skullface @sophshep FYI.
=> users/show: fix company link.

README.md
Update the README based on the current project state.
=> README: various updates.

app/views/home/businesses.html.erb, app/views/home/maintainers.html.erb
Fixing these bugs, which are caused by flexbox being weird in Safari. 
(Once this is shipped and I have a free hour or two, I plan to [update the primer version](https://github.com/ossfriday/ossfriday/issues/92) we're using here, which includes a refactor of our container styles to prevent this very bug.
cc/ @MikeMcQuaid
=> Safari Layout Bug

app/assets/javascripts/application.js, app/assets/javascripts/calendar.js, app/models/user.rb, app/views/home/index.html.erb, app/views/layouts/_nav.html.erb, app/views/users/show.html.erb
Remove some stuff readded in a bad merge, remove commented-out text and tweak the avatar sizes so they are 2x their display size.
=> General cleanup

app/views/home/businesses.html.erb
As noted in https://github.com/ossfriday/ossfriday/pull/73/files#r124367878
CC @willnorris really sorry about that :sob:
=> businesses: fix Will's quote.

app/assets/stylesheets/application.scss
CC @nschonni and @muan
Fixes #107.
=> Remove bike animation on prefers-reduced-motion.

app/controllers/users_controller.rb, config/routes.rb
Ensure that requesting JSON pages or invalid GitHub users are handled better.
=> Better handle bad routes

app/views/users/show.html.erb
See issue #120 for details.
Fixes #120
=> Changed "their" to "your" for logged in users

app/views/home/businesses.html.erb, app/views/home/index.html.erb, app/views/home/maintainers.html.erb
- Use consistent, correct sizes (180px for 90px@2x Retina)
- Use the avatar URL based on the username
- Use the same avatar subdomain everywhere
=> Tweak avatar images

app/controllers/users_controller.rb
Manually sort these events before grouping to ensure the order is consistent.
Fixes #132.
=> users_controller: fix PR/event ordering.

app/views/users/show.html.erb
Ensure that they are separate URLs.
Fixes https://github.com/ossfriday/ossfriday/issues/134
=> users/show: fix output of multiple companies.

app/views/home/index.html.erb, app/views/layouts/application.html.erb, config/locales/en.yml
Various typos that needed fixed.
CC @miurahr can you check the site now and see if you see any mistakes there, too? Thanks!
=> Fixes for i18n PR (#129)

config/locales/en.yml, config/locales/ja.yml
Hi all,
I just found your site and saw that the link is wrong.
This is just a quick fix for it.
Cheers!
=> Fix 'Read the guide' link.

CONTRIBUTING.md, README.md, config/locales/ja.yml
- Detail how to use Transifex
- Link to translations information in README
- Use updated `ja.yml` from @miurahr in Transifex
Fixes #149
=> Translation updates

Gemfile.lock
Let's see how this goes and fix up any problems that result.
Fixes #181.
=> Gemfile.lock: update pg gem.

app/assets/stylesheets/application.scss
=> application: remove unnecessary whitespace.

CONTRIBUTING.md, README.md, app/views/layouts/application.html.erb
This has been moved to the GitHub organisation.
=> Update repository URL

.codecov.yml
These are pretty noisy and already communicated by the status check.
=> codecov.yml: no codecov PR comments.

.codecov.yml
Following the docs at:
https://docs.codecov.io/v4.3.6/docs/pull-request-comments
(should work this time according to CodeCov support)
=> codecov: try again to disable comments.

config/locales/fr.yml
Hello,
This fixes a spelling mistake I introduced in #320 :flushed: 
Also, this adds two inclusive versions for "employees" and "users" that I missed. (Otherwise, in pure academic french, since the masculine form takes precedence over the feminine form, the text would sound like it is addressed to a male audience)
=> Fix french spelling mistakes

config/initializers/locale.rb, config/locales/zh.yml
Hi, Simplified Chinese now meets world.
It is fully translated according English version.
=> add localization for Simplified Chinese

config/locales/zh.yml
First , no idea to used the word `leader` to `领导者` when translating. The word `领导者` 's means refers to the `Great People`, or `Head of State` within simple chinese.
Second, 'first-time' translates to `首次`.
Finally, increase proverb
=> Update chinese translation.

config/initializers/locale.rb, config/locales/ko.yml
Fix the language code and use the same one from Transifex.
=> Fix Korean translation

config/locales/pt.yml
I already had started the translation to portuguese. However, when i synchronized my fork, i saw that translation was concluded. 
So i am submitting some adjustments that i believe are valid.
=> Improving portuguese translation

config/locales/pl.yml
Whoops, this set the default language to Polish!
=> config/locales/pl: fix key name.

config/locales/ja.yml
=> fix link of automation's description url

README.md
Cleanup some Markdown linting complaints.
=> README: general cleanup.

app/views/layouts/application.html.erb
Closes https://github.com/github/communities/issues/308
Remove GA for our 🍪 removal efforts
=> Remove Google Analytics

.rubocop.yml, Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/users_controller.rb, app/helpers/application_helper.rb, app/models/user.rb, app/views/layouts/_calendar.html.erb, config/environments/production.rb, test/helpers/application_helper_test.rb
Also, cleanup YAML and fix all `rubocop` failures.
=> Add, use rubocop-{performance,rails}

.github/dependabot.yml, .github/workflows/tests.yml, config/locales/en.yml
Use the consistent formatting that VS Code's YAML plugin enforces.
=> Autoformat YAML files

.github/workflows/tests.yml
This is no longer needed, it will automatically pull from the file.
=> Remove setting ruby version in action

.github/workflows/tests.yml
This can now be changed now that we've moved to GitHub Pages.
=> workflows/tests: update default branch to main.

_data/locales/zh.yml
=> Correct Chinese language name

_data/locales/de.yml, de/businesses.html, de/index.html, de/maintainers.html
This adds a German translation of [opensourcefriday.com](https://opensourcefriday.com).
=> German translation

_data/locales/de.yml
This PR will add translation for "and" and "friends".
-----
=> Add translation for and and friends

_data/locales/tr.yml, tr/businesses.html, tr/index.html, tr/maintainers.html
-----
Added Turkish translation for Open Source Friday website
=> Add Turkish translation

_data/locales/ja.yml
-----
I found parts that were not translated into Japanese.
I have now corrected into Japanese.
I worked on this Friday, so it was literally an Open Source Friday 😊
=> Correction of missed translation to Japanese

.github/dependabot.yml, .github/workflows/tests.yml, .gitignore
=> fix: github permissions

_data/locales/de.yml
-----
Fix a minor typo (hhttps → https)
=> fix: Correct incorrect URL

_data/locales/de.yml
-----
Correct typos in German document
- Enwicklungsmodelle → Entwicklungsmodelle
- Richtlinine → Richtlinien
=> fix: Correct typos
